---repos:

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.1.1
      hooks:
          - id: mypy
            args: [--no-strict-optional, --ignore-missing-imports]
            # exclude: 

    - repo: local
      hooks:
          - id: unittest
            name: unittest
            entry: python -m unittest discover
            language: python
            types: [python]
            pass_filenames: false
            stages: [commit]
            additional_dependencies: [numpy, scipy, scikit-learn,
                                      scikit-image, matplotlib, PyQt5]

    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: [--profile, black, --filter-files]
            exclude: ^notebooks

    - repo: https://github.com/ambv/black
      rev: 22.3.0
      hooks:
          - id: black
            language_version: python3.10

    - repo: https://github.com/PyCQA/flake8/      rev: 6.0.0      hooks:          - id: flake8            exclude: ^notebooks    # - REPO: HTTPS://GITHUB.COM/JUMANJIHOUSE/PRE-COMMIT-HOOK-YAMLFMT
      # REV: 0.2.2
      # HOOKS:          # - ID: YAMLFMT            # ARGS: [--WIDTH, '150']