---
version: 1
formatters:
    console_frmt:
        format: '%(asctime)s - [%(levelname)s] - "%(message)s"'
        datefmt: '[%H:%M:%S]'
    log_file_frmt:
        format: '%(asctime)s - [%(levelname)s] - %(message)s'
        datefmt: '[%d-%b-%y] [%H:%M:%S]'
handlers:
    console:
        class: logging.StreamHandler
        level: WARNING
        formatter: console_frmt
        stream: ext://sys.stdout
    log_file:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: log_file_frmt
        filename: ./logs/log.txt
        maxBytes: 999999
        backupCount: 10
    notebook:
        class: logging.StreamHandler
        level: INFO  # Adjust the log level as needed (INFO, DEBUG, etc.)
        formatter: console_frmt
root:
    level: DEBUG
    handlers: [console, log_file, notebook]
